<?php

namespace ContainerDI9MJNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gu4Fe_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gu4Fe.c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gu4Fe.c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'module' => ['privates', '.errored.aB13cxp', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\ModuleController::update()": the $module argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcModule".'],
        ], [
            'module' => '?',
        ]);
    }
}
