<?php

namespace ContainerDI9MJNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XNM4IQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xNM4IQH' shared service.
     *
     * @return \App\Entity\AcElement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\ElementController::delete()": the $element argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcElement".');
    }
}
