<?php

namespace ContainerDI9MJNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDAJzwBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XDAJzwB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XDAJzwB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'programmation' => ['privates', '.errored.BGHWgvW', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\ProgrammationController::details()": the $programmation argument is type-hinted with the non-existent class or interface: "App\\Entity\\PrProgrammation".'],
        ], [
            'programmation' => '?',
        ]);
    }
}
