<?php

namespace ContainerDI9MJNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2dGTN8QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2dGTN8Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2dGTN8Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'admission' => ['privates', '.errored..service_locator.2dGTN8Q.App\\Entity\\TAdmission', NULL, 'Cannot autowire service ".service_locator.2dGTN8Q": it references class "App\\Entity\\TAdmission" but no such service exists.'],
        ], [
            'admission' => 'App\\Entity\\TAdmission',
        ]);
    }
}
