<?php

namespace ContainerDI9MJNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTReglement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xJHEfkR.App\Entity\TReglement' shared service.
     *
     * @return \App\Entity\TReglement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xJHEfkR": it references class "App\\Entity\\TReglement" but no such service exists.');
    }
}
