<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240703170115 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tinscription DROP FOREIGN KEY FK_698E3BDE7A45358C');
        $this->addSql('ALTER TABLE tetudiant DROP FOREIGN KEY FK_5F1A7BFDB38A0D28');
        $this->addSql('ALTER TABLE tetudiant DROP FOREIGN KEY FK_5F1A7BFD180AA129');
        $this->addSql('ALTER TABLE tetudiant DROP FOREIGN KEY FK_5F1A7BFDFDFFF0BC');
        $this->addSql('ALTER TABLE tetudiant DROP FOREIGN KEY FK_5F1A7BFDC3E87EF8');
        $this->addSql('ALTER TABLE ac_element DROP FOREIGN KEY FK_E86BDA743BCB2E4B');
        $this->addSql('ALTER TABLE ac_element DROP FOREIGN KEY FK_E86BDA74AFC2B591');
        $this->addSql('ALTER TABLE ac_element DROP FOREIGN KEY FK_E86BDA74316B011F');
        $this->addSql('ALTER TABLE ac_element DROP FOREIGN KEY FK_E86BDA74F987D8A8');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F866032F987D8A8');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F8660321F1F2A24');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F866032F6203804');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F86603247E7B0A1');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F866032F6A260C');
        $this->addSql('ALTER TABLE ac_epreuve DROP FOREIGN KEY FK_7F866032543EC5F0');
        $this->addSql('ALTER TABLE ac_epreuve_penseignant DROP FOREIGN KEY FK_C5F25DD72088B903');
        $this->addSql('ALTER TABLE ac_epreuve_penseignant DROP FOREIGN KEY FK_C5F25DD7D0F570C0');
        $this->addSql('ALTER TABLE ac_module DROP FOREIGN KEY FK_9B0E38C4316B011F');
        $this->addSql('ALTER TABLE ac_module DROP FOREIGN KEY FK_9B0E38C45577AFDB');
        $this->addSql('ALTER TABLE ac_module DROP FOREIGN KEY FK_9B0E38C4F987D8A8');
        $this->addSql('ALTER TABLE anote_externe DROP FOREIGN KEY FK_14885AC2316B011F');
        $this->addSql('ALTER TABLE anote_externe DROP FOREIGN KEY FK_14885AC2F987D8A8');
        $this->addSql('ALTER TABLE anote_externe DROP FOREIGN KEY FK_14885AC2543EC5F0');
        $this->addSql('ALTER TABLE anote_externe DROP FOREIGN KEY FK_14885AC275C9C554');
        $this->addSql('ALTER TABLE ddiplomes DROP FOREIGN KEY FK_825F4BE99002E83');
        $this->addSql('ALTER TABLE ddiplomes DROP FOREIGN KEY FK_825F4BE543EC5F0');
        $this->addSql('ALTER TABLE ddiplomes DROP FOREIGN KEY FK_825F4BEF987D8A8');
        $this->addSql('ALTER TABLE ddiplomes DROP FOREIGN KEY FK_825F4BE7CA20CDB');
        $this->addSql('ALTER TABLE dprediplomes DROP FOREIGN KEY FK_A548621D543EC5F0');
        $this->addSql('ALTER TABLE dprediplomes DROP FOREIGN KEY FK_A548621DC827A17E');
        $this->addSql('ALTER TABLE dprediplomes DROP FOREIGN KEY FK_A548621D26F859E2');
        $this->addSql('ALTER TABLE dprediplomes DROP FOREIGN KEY FK_A548621DF987D8A8');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E5054DAEA18');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E50A76ED395');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E5043B7017B');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E505DAC5993');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E50543EC5F0');
        $this->addSql('ALTER TABLE ex_anotes DROP FOREIGN KEY FK_5E444E50898F2E74');
        $this->addSql('ALTER TABLE ex_controle DROP FOREIGN KEY FK_696A265AA76ED395');
        $this->addSql('ALTER TABLE ex_controle DROP FOREIGN KEY FK_696A265A1F1F2A24');
        $this->addSql('ALTER TABLE ex_controle DROP FOREIGN KEY FK_696A265A543EC5F0');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C4643B7017B');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C46898F2E74');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C461F1F2A24');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C4654DAEA18');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C469B3A819A');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C462456441');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C465DAC5993');
        $this->addSql('ALTER TABLE ex_enotes DROP FOREIGN KEY FK_C5D50C46F987D8A8');
        $this->addSql('ALTER TABLE ex_fnotes DROP FOREIGN KEY FK_43417EE85200282E');
        $this->addSql('ALTER TABLE ex_fnotes DROP FOREIGN KEY FK_43417EE875C9C554');
        $this->addSql('ALTER TABLE ex_fnotes DROP FOREIGN KEY FK_43417EE8F987D8A8');
        $this->addSql('ALTER TABLE ex_gnotes DROP FOREIGN KEY FK_881DAD4D316B011F');
        $this->addSql('ALTER TABLE ex_gnotes DROP FOREIGN KEY FK_881DAD4DF987D8A8');
        $this->addSql('ALTER TABLE ex_gnotes DROP FOREIGN KEY FK_881DAD4D5DAC5993');
        $this->addSql('ALTER TABLE ex_gnotes DROP FOREIGN KEY FK_881DAD4DAB990336');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2B5DAC5993');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2BAFC2B591');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2B43B7017B');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2B898F2E74');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2B54DAEA18');
        $this->addSql('ALTER TABLE ex_mnotes DROP FOREIGN KEY FK_29868E2BA76ED395');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC0898F2E74');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC05577AFDB');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC0A76ED395');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC043B7017B');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC05DAC5993');
        $this->addSql('ALTER TABLE ex_snotes DROP FOREIGN KEY FK_105AEDC054DAEA18');
        $this->addSql('ALTER TABLE halbhon DROP FOREIGN KEY FK_25DB0568139DF194');
        $this->addSql('ALTER TABLE halbhon DROP FOREIGN KEY FK_25DB0568316B011F');
        $this->addSql('ALTER TABLE halbhon DROP FOREIGN KEY FK_25DB0568122EEC90');
        $this->addSql('ALTER TABLE halbhon DROP FOREIGN KEY FK_25DB0568F987D8A8');
        $this->addSql('ALTER TABLE hhonens DROP FOREIGN KEY FK_7D675F0355D5304E');
        $this->addSql('ALTER TABLE hhonens DROP FOREIGN KEY FK_7D675F03F987D8A8');
        $this->addSql('ALTER TABLE hhonens DROP FOREIGN KEY FK_7D675F03E3797A94');
        $this->addSql('ALTER TABLE hhonens DROP FOREIGN KEY FK_7D675F03E455FCC0');
        $this->addSql('ALTER TABLE ins_sanctionner DROP FOREIGN KEY FK_6DA75BF9DCBA8A24');
        $this->addSql('ALTER TABLE ins_sanctionner DROP FOREIGN KEY FK_6DA75BF9316B011F');
        $this->addSql('ALTER TABLE ins_sanctionner DROP FOREIGN KEY FK_6DA75BF9F987D8A8');
        $this->addSql('ALTER TABLE ins_sanctionner DROP FOREIGN KEY FK_6DA75BF95DAC5993');
        $this->addSql('ALTER TABLE ins_sanctionner_sanction DROP FOREIGN KEY FK_47DBBFFACDA93FD6');
        $this->addSql('ALTER TABLE ins_sanctionner_sanction DROP FOREIGN KEY FK_47DBBFFA96E0C11A');
        $this->addSql('ALTER TABLE iseance DROP FOREIGN KEY FK_EDFD8AE5E3797A94');
        $this->addSql('ALTER TABLE iseance DROP FOREIGN KEY FK_EDFD8AE5E455FCC0');
        $this->addSql('ALTER TABLE panonymat_actuel DROP FOREIGN KEY FK_87848275F987D8A8');
        $this->addSql('ALTER TABLE pdiplomes DROP FOREIGN KEY FK_F909E7C3F987D8A8');
        $this->addSql('ALTER TABLE pdiplomes DROP FOREIGN KEY FK_F909E7C35200282E');
        $this->addSql('ALTER TABLE pdocument DROP FOREIGN KEY FK_ABE182646C97ED8F');
        $this->addSql('ALTER TABLE pdocument DROP FOREIGN KEY FK_ABE18264FF631228');
        $this->addSql('ALTER TABLE penseignant DROP FOREIGN KEY FK_F788A4C8FE19A1A8');
        $this->addSql('ALTER TABLE penseignant_except DROP FOREIGN KEY FK_21EAB96BE455FCC0');
        $this->addSql('ALTER TABLE penseignant_except DROP FOREIGN KEY FK_21EAB96B139C32BD');
        $this->addSql('ALTER TABLE penseignant_except DROP FOREIGN KEY FK_21EAB96B5200282E');
        $this->addSql('ALTER TABLE penseignant_pr_programmation DROP FOREIGN KEY FK_744AE189882AE92');
        $this->addSql('ALTER TABLE penseignant_pr_programmation DROP FOREIGN KEY FK_744AE18D0F570C0');
        $this->addSql('ALTER TABLE pensgrille DROP FOREIGN KEY FK_7E46E6C6B69AD513');
        $this->addSql('ALTER TABLE pensgrille DROP FOREIGN KEY FK_7E46E6C6139C32BD');
        $this->addSql('ALTER TABLE pensgrille DROP FOREIGN KEY FK_7E46E6C6FE19A1A8');
        $this->addSql('ALTER TABLE pensgrille DROP FOREIGN KEY FK_7E46E6C65200282E');
        $this->addSql('ALTER TABLE pgroupe DROP FOREIGN KEY FK_C47F22D77A45358C');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A664316B011F');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A6647A45358C');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A664DC304035');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A664122EEC90');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A66438FAD351');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A66496D6BD09');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A664F987D8A8');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A6641460EA3F');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A664493FDC38');
        $this->addSql('ALTER TABLE pl_emptime DROP FOREIGN KEY FK_F974A6649CE097A8');
        $this->addSql('ALTER TABLE pl_emptimens DROP FOREIGN KEY FK_4D8F255AE455FCC0');
        $this->addSql('ALTER TABLE pl_emptimens DROP FOREIGN KEY FK_4D8F255AE3797A94');
        $this->addSql('ALTER TABLE pr_programmation DROP FOREIGN KEY FK_BD732A7B543EC5F0');
        $this->addSql('ALTER TABLE pr_programmation DROP FOREIGN KEY FK_BD732A7B1F1F2A24');
        $this->addSql('ALTER TABLE pr_programmation DROP FOREIGN KEY FK_BD732A7BF987D8A8');
        $this->addSql('ALTER TABLE pr_programmation DROP FOREIGN KEY FK_BD732A7B47E7B0A1');
        $this->addSql('ALTER TABLE psalles DROP FOREIGN KEY FK_B95BEB5C984CE93F');
        $this->addSql('ALTER TABLE pv DROP FOREIGN KEY FK_D780BF00316B011F');
        $this->addSql('ALTER TABLE pv DROP FOREIGN KEY FK_D780BF00F987D8A8');
        $this->addSql('ALTER TABLE pv DROP FOREIGN KEY FK_D780BF00543EC5F0');
        $this->addSql('ALTER TABLE pv DROP FOREIGN KEY FK_D780BF005577AFDB');
        $this->addSql('ALTER TABLE sanction DROP FOREIGN KEY FK_6D6491AFDCBA8A24');
        $this->addSql('ALTER TABLE sous_agression DROP FOREIGN KEY FK_8769C2BADCBA8A24');
        $this->addSql('ALTER TABLE tadmission_document DROP FOREIGN KEY FK_7FF4AB51C33F7837');
        $this->addSql('ALTER TABLE tadmission_document DROP FOREIGN KEY FK_7FF4AB518337288');
        $this->addSql('ALTER TABLE tinscription_imp_controle DROP FOREIGN KEY FK_15479A7F987D8A8');
        $this->addSql('ALTER TABLE tinscription_imp_controle DROP FOREIGN KEY FK_15479A75DAC5993');
        $this->addSql('ALTER TABLE tinscription_imp_log DROP FOREIGN KEY FK_50C9904FF987D8A8');
        $this->addSql('ALTER TABLE tinscription_imp_log DROP FOREIGN KEY FK_50C9904F5DAC5993');
        $this->addSql('ALTER TABLE tpreinscription_pdocument DROP FOREIGN KEY FK_48644EF364070F36');
        $this->addSql('ALTER TABLE tpreinscription_pdocument DROP FOREIGN KEY FK_48644EF3F7278E40');
        $this->addSql('ALTER TABLE tpreinscription_releve_note DROP FOREIGN KEY FK_F7B23EACF987D8A8');
        $this->addSql('ALTER TABLE tpreinscription_releve_note DROP FOREIGN KEY FK_F7B23EACDDEAB1A3');
        $this->addSql('ALTER TABLE tpreinscription_releve_note DROP FOREIGN KEY FK_F7B23EACF46CD258');
        $this->addSql('DROP TABLE ac_element');
        $this->addSql('DROP TABLE ac_epreuve');
        $this->addSql('DROP TABLE ac_epreuve_penseignant');
        $this->addSql('DROP TABLE ac_module');
        $this->addSql('DROP TABLE agression');
        $this->addSql('DROP TABLE anote_externe');
        $this->addSql('DROP TABLE checkinout');
        $this->addSql('DROP TABLE ddiplomes');
        $this->addSql('DROP TABLE dprediplomes');
        $this->addSql('DROP TABLE ex_anotes');
        $this->addSql('DROP TABLE ex_controle');
        $this->addSql('DROP TABLE ex_enotes');
        $this->addSql('DROP TABLE ex_fnotes');
        $this->addSql('DROP TABLE ex_gnotes');
        $this->addSql('DROP TABLE ex_mnotes');
        $this->addSql('DROP TABLE ex_snotes');
        $this->addSql('DROP TABLE halbhon');
        $this->addSql('DROP TABLE hhonens');
        $this->addSql('DROP TABLE hhonens_annuler');
        $this->addSql('DROP TABLE ins_sanctionner');
        $this->addSql('DROP TABLE ins_sanctionner_sanction');
        $this->addSql('DROP TABLE iseance');
        $this->addSql('DROP TABLE iseance_salle');
        $this->addSql('DROP TABLE machines');
        $this->addSql('DROP TABLE panonymat_actuel');
        $this->addSql('DROP TABLE pdiplomes');
        $this->addSql('DROP TABLE pdocument');
        $this->addSql('DROP TABLE penseignant');
        $this->addSql('DROP TABLE penseignant_except');
        $this->addSql('DROP TABLE penseignant_pr_programmation');
        $this->addSql('DROP TABLE pensgrille');
        $this->addSql('DROP TABLE pe_statut');
        $this->addSql('DROP TABLE pgrade');
        $this->addSql('DROP TABLE pgroupe');
        $this->addSql('DROP TABLE pl_emptime');
        $this->addSql('DROP TABLE pl_emptimens');
        $this->addSql('DROP TABLE pmatiere');
        $this->addSql('DROP TABLE pnature_epreuve');
        $this->addSql('DROP TABLE pr_programmation');
        $this->addSql('DROP TABLE psalles');
        $this->addSql('DROP TABLE psignataire');
        $this->addSql('DROP TABLE pv');
        $this->addSql('DROP TABLE sanction');
        $this->addSql('DROP TABLE semaine');
        $this->addSql('DROP TABLE semaines');
        $this->addSql('DROP TABLE sous_agression');
        $this->addSql('DROP TABLE tadmission_document');
        $this->addSql('DROP TABLE tinscription_imp_controle');
        $this->addSql('DROP TABLE tinscription_imp_log');
        $this->addSql('DROP TABLE tpreinscription_pdocument');
        $this->addSql('DROP TABLE tpreinscription_releve_note');
        $this->addSql('DROP TABLE type_element');
        $this->addSql('DROP TABLE userinfo');
        $this->addSql('DROP TABLE xacademie');
        $this->addSql('DROP TABLE xfiliere');
        $this->addSql('DROP TABLE xlangue');
        $this->addSql('DROP TABLE xseance');
        $this->addSql('DROP TABLE xseance_absences');
        $this->addSql('DROP TABLE xseance_capitaliser');
        $this->addSql('DROP TABLE xseance_motif_abs');
        $this->addSql('DROP TABLE xserie_bac');
        $this->addSql('DROP TABLE xtype_bac');
        $this->addSql('DROP INDEX IDX_5F1A7BFD180AA129 ON tetudiant');
        $this->addSql('DROP INDEX IDX_5F1A7BFDC3E87EF8 ON tetudiant');
        $this->addSql('DROP INDEX IDX_5F1A7BFDB38A0D28 ON tetudiant');
        $this->addSql('DROP INDEX IDX_5F1A7BFDFDFFF0BC ON tetudiant');
        $this->addSql('ALTER TABLE tetudiant DROP type_bac_id, DROP academie_id, DROP langue_concours_id, DROP filiere_id');
        $this->addSql('DROP INDEX IDX_698E3BDE7A45358C ON tinscription');
        $this->addSql('ALTER TABLE tinscription DROP groupe_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ac_element (id INT AUTO_INCREMENT NOT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, module_id INT DEFAULT NULL, nature_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, couleur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, coefficient DOUBLE PRECISION DEFAULT NULL, coefficient_epreuve JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', type INT DEFAULT NULL, cours_document INT DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, INDEX IDX_E86BDA74316B011F (user_updated_id), INDEX IDX_E86BDA74AFC2B591 (module_id), INDEX IDX_E86BDA743BCB2E4B (nature_id), INDEX IDX_E86BDA74F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ac_epreuve (id INT AUTO_INCREMENT NOT NULL, annee_id INT DEFAULT NULL, element_id INT DEFAULT NULL, nature_epreuve_id INT DEFAULT NULL, statut_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_validated_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, coefficient INT DEFAULT NULL, date_epreuve DATE DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, anonymat INT DEFAULT NULL, created DATETIME DEFAULT NULL, nature VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, validated DATETIME DEFAULT NULL, INDEX IDX_7F866032F6A260C (user_validated_id), INDEX IDX_7F86603247E7B0A1 (nature_epreuve_id), INDEX IDX_7F866032F6203804 (statut_id), INDEX IDX_7F866032543EC5F0 (annee_id), INDEX IDX_7F866032F987D8A8 (user_created_id), INDEX IDX_7F8660321F1F2A24 (element_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ac_epreuve_penseignant (ac_epreuve_id INT NOT NULL, penseignant_id INT NOT NULL, INDEX IDX_C5F25DD7D0F570C0 (penseignant_id), INDEX IDX_C5F25DD72088B903 (ac_epreuve_id), PRIMARY KEY(ac_epreuve_id, penseignant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ac_module (id INT AUTO_INCREMENT NOT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, coefficient DOUBLE PRECISION DEFAULT NULL, type VARCHAR(1) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, color VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_9B0E38C45577AFDB (semestre_id), INDEX IDX_9B0E38C4F987D8A8 (user_created_id), INDEX IDX_9B0E38C4316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agression (id INT AUTO_INCREMENT NOT NULL, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE anote_externe (id INT AUTO_INCREMENT NOT NULL, admission_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, INDEX IDX_14885AC2F987D8A8 (user_created_id), INDEX IDX_14885AC2316B011F (user_updated_id), INDEX IDX_14885AC275C9C554 (admission_id), INDEX IDX_14885AC2543EC5F0 (annee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE checkinout (id INT AUTO_INCREMENT NOT NULL, userid INT DEFAULT NULL, checktime DATETIME DEFAULT NULL, memoinfo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, sn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, checktype VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ddiplomes (id INT AUTO_INCREMENT NOT NULL, prediplome_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, signataire_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, note DOUBLE PRECISION DEFAULT NULL, date DATE DEFAULT NULL, created DATETIME DEFAULT NULL, INDEX IDX_825F4BE7CA20CDB (signataire_id), INDEX IDX_825F4BE99002E83 (prediplome_id), INDEX IDX_825F4BE543EC5F0 (annee_id), INDEX IDX_825F4BEF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE dprediplomes (id INT AUTO_INCREMENT NOT NULL, fnote_id INT DEFAULT NULL, diplome_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, code VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, note DOUBLE PRECISION DEFAULT NULL, mention VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, INDEX IDX_A548621D543EC5F0 (annee_id), INDEX IDX_A548621DC827A17E (fnote_id), INDEX IDX_A548621D26F859E2 (diplome_id), INDEX IDX_A548621DF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_anotes (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, user_id INT DEFAULT NULL, statut_s2_id INT DEFAULT NULL, statut_aff_id INT DEFAULT NULL, statut_def_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, note_sec DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, categorie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_5E444E5054DAEA18 (statut_aff_id), INDEX IDX_5E444E50543EC5F0 (annee_id), INDEX IDX_5E444E5043B7017B (statut_def_id), INDEX IDX_5E444E50A76ED395 (user_id), INDEX IDX_5E444E50898F2E74 (statut_s2_id), UNIQUE INDEX UNIQ_5E444E505DAC5993 (inscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_controle (id INT AUTO_INCREMENT NOT NULL, element_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, user_id INT DEFAULT NULL, mcc TINYINT(1) DEFAULT NULL, mtp TINYINT(1) DEFAULT NULL, mef TINYINT(1) DEFAULT NULL, efr TINYINT(1) DEFAULT NULL, ccr TINYINT(1) DEFAULT NULL, tpr TINYINT(1) DEFAULT NULL, melement TINYINT(1) DEFAULT NULL, mmodule TINYINT(1) DEFAULT NULL, msemestre TINYINT(1) DEFAULT NULL, mannee TINYINT(1) DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, active TINYINT(1) DEFAULT NULL, simulation TINYINT(1) DEFAULT NULL, INDEX IDX_696A265A543EC5F0 (annee_id), INDEX IDX_696A265AA76ED395 (user_id), INDEX IDX_696A265A1F1F2A24 (element_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_enotes (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, element_id INT DEFAULT NULL, statut_s1_id INT DEFAULT NULL, statut_s2_id INT DEFAULT NULL, statut_def_id INT DEFAULT NULL, statut_aff_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, statut_rachat_id INT DEFAULT NULL, mcc DOUBLE PRECISION DEFAULT NULL, mtp DOUBLE PRECISION DEFAULT NULL, mef DOUBLE PRECISION DEFAULT NULL, ccr DOUBLE PRECISION DEFAULT NULL, tpr DOUBLE PRECISION DEFAULT NULL, efr DOUBLE PRECISION DEFAULT NULL, note_ini DOUBLE PRECISION DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, note_rat DOUBLE PRECISION DEFAULT NULL, note_rachat DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cc_rachat DOUBLE PRECISION DEFAULT NULL, tp_rachat DOUBLE PRECISION DEFAULT NULL, ef_rachat DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, pond_mef INT DEFAULT NULL, pond_efr INT DEFAULT NULL, statut_affichage INT DEFAULT NULL, INDEX IDX_C5D50C46F987D8A8 (user_created_id), INDEX IDX_C5D50C46898F2E74 (statut_s2_id), INDEX IDX_C5D50C465DAC5993 (inscription_id), INDEX IDX_C5D50C462456441 (statut_rachat_id), INDEX IDX_C5D50C4643B7017B (statut_def_id), INDEX IDX_C5D50C461F1F2A24 (element_id), INDEX IDX_C5D50C4654DAEA18 (statut_aff_id), INDEX IDX_C5D50C469B3A819A (statut_s1_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_fnotes (id INT AUTO_INCREMENT NOT NULL, admission_id INT DEFAULT NULL, formation_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, note_sec DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, flag DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, INDEX IDX_43417EE875C9C554 (admission_id), INDEX IDX_43417EE85200282E (formation_id), INDEX IDX_43417EE8F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_gnotes (id INT AUTO_INCREMENT NOT NULL, epreuve_id INT DEFAULT NULL, inscription_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, anonymat INT DEFAULT NULL, absence TINYINT(1) DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, statut_affichage INT DEFAULT NULL, INDEX IDX_881DAD4D316B011F (user_updated_id), INDEX IDX_881DAD4DAB990336 (epreuve_id), INDEX IDX_881DAD4D5DAC5993 (inscription_id), INDEX IDX_881DAD4DF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_mnotes (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, module_id INT DEFAULT NULL, user_id INT DEFAULT NULL, statut_s2_id INT DEFAULT NULL, statut_def_id INT DEFAULT NULL, statut_aff_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, note_ini DOUBLE PRECISION DEFAULT NULL, note_rat DOUBLE PRECISION DEFAULT NULL, note_rachat DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, INDEX IDX_29868E2B43B7017B (statut_def_id), INDEX IDX_29868E2BAFC2B591 (module_id), INDEX IDX_29868E2B54DAEA18 (statut_aff_id), INDEX IDX_29868E2BA76ED395 (user_id), INDEX IDX_29868E2B898F2E74 (statut_s2_id), INDEX IDX_29868E2B5DAC5993 (inscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ex_snotes (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, user_id INT DEFAULT NULL, statut_s2_id INT DEFAULT NULL, statut_def_id INT DEFAULT NULL, statut_aff_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, note_sec DOUBLE PRECISION DEFAULT NULL, note_rachat DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, categorie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, INDEX IDX_105AEDC05DAC5993 (inscription_id), INDEX IDX_105AEDC043B7017B (statut_def_id), INDEX IDX_105AEDC05577AFDB (semestre_id), INDEX IDX_105AEDC054DAEA18 (statut_aff_id), INDEX IDX_105AEDC0A76ED395 (user_id), INDEX IDX_105AEDC0898F2E74 (statut_s2_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE halbhon (id INT AUTO_INCREMENT NOT NULL, semaine_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, promotion_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, INDEX IDX_25DB0568139DF194 (promotion_id), INDEX IDX_25DB0568122EEC90 (semaine_id), INDEX IDX_25DB0568F987D8A8 (user_created_id), INDEX IDX_25DB0568316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE hhonens (id INT AUTO_INCREMENT NOT NULL, enseignant_id INT DEFAULT NULL, seance_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, bordereau_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, nbr_heur DOUBLE PRECISION DEFAULT NULL, montant INT DEFAULT NULL, statut VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, annuler DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, annulated DATETIME DEFAULT NULL, exept DOUBLE PRECISION DEFAULT NULL, nbr_sc_regroupe INT DEFAULT NULL, date_reglement DATETIME DEFAULT NULL, brut INT DEFAULT NULL, ir INT DEFAULT NULL, INDEX IDX_7D675F03E3797A94 (seance_id), INDEX IDX_7D675F03F987D8A8 (user_created_id), INDEX IDX_7D675F0355D5304E (bordereau_id), INDEX IDX_7D675F03E455FCC0 (enseignant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE hhonens_annuler (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, nbr_heur INT DEFAULT NULL, enseignant INT DEFAULT NULL, seance INT DEFAULT NULL, usercreated INT DEFAULT NULL, bordereau INT DEFAULT NULL, montant INT DEFAULT NULL, statut VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, annuler DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, exept DOUBLE PRECISION DEFAULT NULL, nbr_sc_regroupe DOUBLE PRECISION DEFAULT NULL, date_reglement DATETIME DEFAULT NULL, user_annuled INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ins_sanctionner (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, agression_id INT DEFAULT NULL, date_incident DATE DEFAULT NULL, date_reunion DATETIME DEFAULT NULL, date_decision DATETIME DEFAULT NULL, active DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, valide DOUBLE PRECISION DEFAULT NULL, autre_sanction LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\', code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, autre_agression VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, sans_suite DOUBLE PRECISION DEFAULT NULL, INDEX IDX_6DA75BF9316B011F (user_updated_id), INDEX IDX_6DA75BF9DCBA8A24 (agression_id), INDEX IDX_6DA75BF95DAC5993 (inscription_id), INDEX IDX_6DA75BF9F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ins_sanctionner_sanction (ins_sanctionner_id INT NOT NULL, sanction_id INT NOT NULL, INDEX IDX_47DBBFFACDA93FD6 (ins_sanctionner_id), INDEX IDX_47DBBFFA96E0C11A (sanction_id), PRIMARY KEY(ins_sanctionner_id, sanction_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE iseance (id INT AUTO_INCREMENT NOT NULL, seance_id INT DEFAULT NULL, enseignant_id INT DEFAULT NULL, statut INT DEFAULT NULL, INDEX IDX_EDFD8AE5E3797A94 (seance_id), INDEX IDX_EDFD8AE5E455FCC0 (enseignant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE iseance_salle (id INT AUTO_INCREMENT NOT NULL, code_salle VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_pointeuse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, emplacement VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE machines (id INT AUTO_INCREMENT NOT NULL, machine_alias VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, sn VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE panonymat_actuel (id INT AUTO_INCREMENT NOT NULL, user_created_id INT DEFAULT NULL, code VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, INDEX IDX_87848275F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pdiplomes (id INT AUTO_INCREMENT NOT NULL, formation_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, code VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, INDEX IDX_F909E7C3F987D8A8 (user_created_id), INDEX IDX_F909E7C35200282E (formation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pdocument (id INT AUTO_INCREMENT NOT NULL, etablissement_id INT DEFAULT NULL, nature_demande_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, attribution VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active TINYINT(1) DEFAULT NULL, INDEX IDX_ABE182646C97ED8F (nature_demande_id), INDEX IDX_ABE18264FF631228 (etablissement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE penseignant (id INT AUTO_INCREMENT NOT NULL, grade_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, active INT DEFAULT NULL, cin VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rib VARCHAR(24) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_F788A4C8FE19A1A8 (grade_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE penseignant_except (id INT AUTO_INCREMENT NOT NULL, enseignant_id INT DEFAULT NULL, formation_id INT DEFAULT NULL, usercreated_id INT DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_21EAB96B5200282E (formation_id), INDEX IDX_21EAB96B139C32BD (usercreated_id), INDEX IDX_21EAB96BE455FCC0 (enseignant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE penseignant_pr_programmation (penseignant_id INT NOT NULL, pr_programmation_id INT NOT NULL, INDEX IDX_744AE18D0F570C0 (penseignant_id), INDEX IDX_744AE189882AE92 (pr_programmation_id), PRIMARY KEY(penseignant_id, pr_programmation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pensgrille (id INT AUTO_INCREMENT NOT NULL, grade_id INT DEFAULT NULL, formation_id INT DEFAULT NULL, type_epreuve_id INT DEFAULT NULL, usercreated_id INT DEFAULT NULL, montant INT DEFAULT NULL, created DATETIME DEFAULT NULL, nature VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_7E46E6C6139C32BD (usercreated_id), INDEX IDX_7E46E6C6FE19A1A8 (grade_id), INDEX IDX_7E46E6C65200282E (formation_id), INDEX IDX_7E46E6C6B69AD513 (type_epreuve_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pe_statut (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pgrade (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pgroupe (id INT AUTO_INCREMENT NOT NULL, groupe_id INT DEFAULT NULL, niveau VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_C47F22D77A45358C (groupe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pl_emptime (id INT AUTO_INCREMENT NOT NULL, programmation_id INT DEFAULT NULL, semaine_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, salle_id INT DEFAULT NULL, groupe_id INT DEFAULT NULL, xsalle_id INT DEFAULT NULL, user_deleted_id INT DEFAULT NULL, assure_par_id INT DEFAULT NULL, user_verified_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, dateemploi DATETIME DEFAULT NULL, start DATETIME DEFAULT NULL, end DATETIME DEFAULT NULL, heur_db TIME DEFAULT NULL, heur_fin TIME DEFAULT NULL, valider DOUBLE PRECISION DEFAULT NULL, annuler DOUBLE PRECISION DEFAULT NULL, generer DOUBLE PRECISION DEFAULT NULL, motif_annuler VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, active DOUBLE PRECISION DEFAULT NULL, deleted DATETIME DEFAULT NULL, observation LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, verifier DOUBLE PRECISION DEFAULT NULL, verified DATETIME DEFAULT NULL, INDEX IDX_F974A66438FAD351 (user_deleted_id), INDEX IDX_F974A664DC304035 (salle_id), INDEX IDX_F974A664122EEC90 (semaine_id), INDEX IDX_F974A6649CE097A8 (assure_par_id), INDEX IDX_F974A6647A45358C (groupe_id), INDEX IDX_F974A664F987D8A8 (user_created_id), INDEX IDX_F974A664493FDC38 (user_verified_id), INDEX IDX_F974A6641460EA3F (xsalle_id), INDEX IDX_F974A664316B011F (user_updated_id), INDEX IDX_F974A66496D6BD09 (programmation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pl_emptimens (id INT AUTO_INCREMENT NOT NULL, seance_id INT DEFAULT NULL, enseignant_id INT DEFAULT NULL, generer DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, active DOUBLE PRECISION DEFAULT NULL, INDEX IDX_4D8F255AE3797A94 (seance_id), INDEX IDX_4D8F255AE455FCC0 (enseignant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pmatiere (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pnature_epreuve (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, nature VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, examen INT DEFAULT NULL, mapped VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, absence TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pr_programmation (id INT AUTO_INCREMENT NOT NULL, element_id INT DEFAULT NULL, nature_epreuve_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, volume DOUBLE PRECISION DEFAULT NULL, observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, regroupe INT DEFAULT NULL, categorie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, INDEX IDX_BD732A7B543EC5F0 (annee_id), INDEX IDX_BD732A7B1F1F2A24 (element_id), INDEX IDX_BD732A7B47E7B0A1 (nature_epreuve_id), INDEX IDX_BD732A7BF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE psalles (id INT AUTO_INCREMENT NOT NULL, etage_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, x_ip VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, etat_pc DOUBLE PRECISION DEFAULT NULL, attente INT DEFAULT NULL, groupe VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, INDEX IDX_B95BEB5C984CE93F (etage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE psignataire (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pv (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, president VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, coordonnateur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, membres VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, doc_asso VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, active DOUBLE PRECISION DEFAULT NULL, seuil_rachat DOUBLE PRECISION DEFAULT NULL, observation LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_D780BF00316B011F (user_updated_id), INDEX IDX_D780BF005577AFDB (semestre_id), INDEX IDX_D780BF00543EC5F0 (annee_id), INDEX IDX_D780BF00F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE sanction (id INT AUTO_INCREMENT NOT NULL, agression_id INT DEFAULT NULL, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active DOUBLE PRECISION DEFAULT NULL, INDEX IDX_6D6491AFDCBA8A24 (agression_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE semaine (id INT AUTO_INCREMENT NOT NULL, nsemaine INT DEFAULT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, tranche SMALLINT DEFAULT NULL, position SMALLINT DEFAULT NULL, annee_s VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE semaines (id INT AUTO_INCREMENT NOT NULL, semaine INT DEFAULT NULL, dated VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, datef VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, tranche INT DEFAULT NULL, position VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, anneés VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE sous_agression (id INT AUTO_INCREMENT NOT NULL, agression_id INT DEFAULT NULL, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active DOUBLE PRECISION DEFAULT NULL, INDEX IDX_8769C2BADCBA8A24 (agression_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tadmission_document (id INT AUTO_INCREMENT NOT NULL, preinscription_id INT DEFAULT NULL, document_id INT DEFAULT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_7FF4AB518337288 (preinscription_id), INDEX IDX_7FF4AB51C33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tinscription_imp_controle (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, controle INT DEFAULT NULL, is_rattrapage TINYINT(1) DEFAULT NULL, created DATETIME DEFAULT NULL, INDEX IDX_15479A75DAC5993 (inscription_id), INDEX IDX_15479A7F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tinscription_imp_log (id INT AUTO_INCREMENT NOT NULL, inscription_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, nombre_etiquettes INT DEFAULT NULL, controle INT DEFAULT NULL, is_rattrapage TINYINT(1) DEFAULT NULL, created DATETIME DEFAULT NULL, INDEX IDX_50C9904FF987D8A8 (user_created_id), INDEX IDX_50C9904F5DAC5993 (inscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tpreinscription_pdocument (tpreinscription_id INT NOT NULL, pdocument_id INT NOT NULL, INDEX IDX_48644EF3F7278E40 (pdocument_id), INDEX IDX_48644EF364070F36 (tpreinscription_id), PRIMARY KEY(tpreinscription_id, pdocument_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tpreinscription_releve_note (id INT AUTO_INCREMENT NOT NULL, matiere_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, created DATETIME DEFAULT NULL, INDEX IDX_F7B23EACDDEAB1A3 (etudiant_id), INDEX IDX_F7B23EACF987D8A8 (user_created_id), INDEX IDX_F7B23EACF46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE type_element (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE userinfo (id INT AUTO_INCREMENT NOT NULL, userid INT DEFAULT NULL, badgenumber VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, street VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, defaultdeptid SMALLINT DEFAULT NULL, ophone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xacademie (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xfiliere (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xlangue (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xseance (id INT AUTO_INCREMENT NOT NULL, id_feuillea VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_séance INT DEFAULT NULL, typeséance VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_etablissement VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_formation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_promotion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_année VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, année_lib VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_semestre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, groupe VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_module VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_element VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_enseignant VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_salle VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_séance DATE DEFAULT NULL, semaine INT DEFAULT NULL, heure_debut TIME DEFAULT NULL, heure_fin TIME DEFAULT NULL, traitement INT DEFAULT NULL, cloturer INT DEFAULT NULL, date_sys DATE DEFAULT NULL, statut INT DEFAULT NULL, existe INT DEFAULT NULL, signé INT DEFAULT NULL, annulée INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xseance_absences (id INT AUTO_INCREMENT NOT NULL, id_admission VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_séance INT DEFAULT NULL, id_user INT DEFAULT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, prénom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_groupe_stage VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_pointage DATE DEFAULT NULL, heure_pointage TIME DEFAULT NULL, retard VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, categorie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, categorie_enseig VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, justifier SMALLINT DEFAULT NULL, id_justif SMALLINT DEFAULT NULL, motif SMALLINT DEFAULT NULL, comptabilisé INT DEFAULT NULL, date_sys DATE DEFAULT NULL, obs VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, categorie_si VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, categorie_f VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xseance_capitaliser (id INT AUTO_INCREMENT NOT NULL, id_admission VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_promotion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_module VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_semestre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, id_année VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_sys DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xseance_motif_abs (id INT AUTO_INCREMENT NOT NULL, motif VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xserie_bac (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE xtype_bac (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, abreviation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, active INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE ac_element ADD CONSTRAINT FK_E86BDA743BCB2E4B FOREIGN KEY (nature_id) REFERENCES type_element (id)');
        $this->addSql('ALTER TABLE ac_element ADD CONSTRAINT FK_E86BDA74AFC2B591 FOREIGN KEY (module_id) REFERENCES ac_module (id)');
        $this->addSql('ALTER TABLE ac_element ADD CONSTRAINT FK_E86BDA74316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ac_element ADD CONSTRAINT FK_E86BDA74F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F866032F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F8660321F1F2A24 FOREIGN KEY (element_id) REFERENCES ac_element (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F866032F6203804 FOREIGN KEY (statut_id) REFERENCES pstatut (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F86603247E7B0A1 FOREIGN KEY (nature_epreuve_id) REFERENCES pnature_epreuve (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F866032F6A260C FOREIGN KEY (user_validated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ac_epreuve ADD CONSTRAINT FK_7F866032543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE ac_epreuve_penseignant ADD CONSTRAINT FK_C5F25DD72088B903 FOREIGN KEY (ac_epreuve_id) REFERENCES ac_epreuve (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ac_epreuve_penseignant ADD CONSTRAINT FK_C5F25DD7D0F570C0 FOREIGN KEY (penseignant_id) REFERENCES penseignant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ac_module ADD CONSTRAINT FK_9B0E38C4316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ac_module ADD CONSTRAINT FK_9B0E38C45577AFDB FOREIGN KEY (semestre_id) REFERENCES ac_semestre (id)');
        $this->addSql('ALTER TABLE ac_module ADD CONSTRAINT FK_9B0E38C4F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE anote_externe ADD CONSTRAINT FK_14885AC2316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE anote_externe ADD CONSTRAINT FK_14885AC2F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE anote_externe ADD CONSTRAINT FK_14885AC2543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE anote_externe ADD CONSTRAINT FK_14885AC275C9C554 FOREIGN KEY (admission_id) REFERENCES tadmission (id)');
        $this->addSql('ALTER TABLE ddiplomes ADD CONSTRAINT FK_825F4BE99002E83 FOREIGN KEY (prediplome_id) REFERENCES dprediplomes (id)');
        $this->addSql('ALTER TABLE ddiplomes ADD CONSTRAINT FK_825F4BE543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE ddiplomes ADD CONSTRAINT FK_825F4BEF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ddiplomes ADD CONSTRAINT FK_825F4BE7CA20CDB FOREIGN KEY (signataire_id) REFERENCES psignataire (id)');
        $this->addSql('ALTER TABLE dprediplomes ADD CONSTRAINT FK_A548621D543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE dprediplomes ADD CONSTRAINT FK_A548621DC827A17E FOREIGN KEY (fnote_id) REFERENCES ex_fnotes (id)');
        $this->addSql('ALTER TABLE dprediplomes ADD CONSTRAINT FK_A548621D26F859E2 FOREIGN KEY (diplome_id) REFERENCES pdiplomes (id)');
        $this->addSql('ALTER TABLE dprediplomes ADD CONSTRAINT FK_A548621DF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E5054DAEA18 FOREIGN KEY (statut_aff_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E50A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E5043B7017B FOREIGN KEY (statut_def_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E505DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E50543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE ex_anotes ADD CONSTRAINT FK_5E444E50898F2E74 FOREIGN KEY (statut_s2_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_controle ADD CONSTRAINT FK_696A265AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_controle ADD CONSTRAINT FK_696A265A1F1F2A24 FOREIGN KEY (element_id) REFERENCES ac_element (id)');
        $this->addSql('ALTER TABLE ex_controle ADD CONSTRAINT FK_696A265A543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C4643B7017B FOREIGN KEY (statut_def_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C46898F2E74 FOREIGN KEY (statut_s2_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C461F1F2A24 FOREIGN KEY (element_id) REFERENCES ac_element (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C4654DAEA18 FOREIGN KEY (statut_aff_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C469B3A819A FOREIGN KEY (statut_s1_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C462456441 FOREIGN KEY (statut_rachat_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C465DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ex_enotes ADD CONSTRAINT FK_C5D50C46F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_fnotes ADD CONSTRAINT FK_43417EE85200282E FOREIGN KEY (formation_id) REFERENCES ac_formation (id)');
        $this->addSql('ALTER TABLE ex_fnotes ADD CONSTRAINT FK_43417EE875C9C554 FOREIGN KEY (admission_id) REFERENCES tadmission (id)');
        $this->addSql('ALTER TABLE ex_fnotes ADD CONSTRAINT FK_43417EE8F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_gnotes ADD CONSTRAINT FK_881DAD4D316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_gnotes ADD CONSTRAINT FK_881DAD4DF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_gnotes ADD CONSTRAINT FK_881DAD4D5DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ex_gnotes ADD CONSTRAINT FK_881DAD4DAB990336 FOREIGN KEY (epreuve_id) REFERENCES ac_epreuve (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2B5DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2BAFC2B591 FOREIGN KEY (module_id) REFERENCES ac_module (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2B43B7017B FOREIGN KEY (statut_def_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2B898F2E74 FOREIGN KEY (statut_s2_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2B54DAEA18 FOREIGN KEY (statut_aff_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_mnotes ADD CONSTRAINT FK_29868E2BA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC0898F2E74 FOREIGN KEY (statut_s2_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC05577AFDB FOREIGN KEY (semestre_id) REFERENCES ac_semestre (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC043B7017B FOREIGN KEY (statut_def_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC05DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ex_snotes ADD CONSTRAINT FK_105AEDC054DAEA18 FOREIGN KEY (statut_aff_id) REFERENCES pe_statut (id)');
        $this->addSql('ALTER TABLE halbhon ADD CONSTRAINT FK_25DB0568139DF194 FOREIGN KEY (promotion_id) REFERENCES ac_promotion (id)');
        $this->addSql('ALTER TABLE halbhon ADD CONSTRAINT FK_25DB0568316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE halbhon ADD CONSTRAINT FK_25DB0568122EEC90 FOREIGN KEY (semaine_id) REFERENCES semaine (id)');
        $this->addSql('ALTER TABLE halbhon ADD CONSTRAINT FK_25DB0568F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE hhonens ADD CONSTRAINT FK_7D675F0355D5304E FOREIGN KEY (bordereau_id) REFERENCES halbhon (id)');
        $this->addSql('ALTER TABLE hhonens ADD CONSTRAINT FK_7D675F03F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE hhonens ADD CONSTRAINT FK_7D675F03E3797A94 FOREIGN KEY (seance_id) REFERENCES pl_emptime (id)');
        $this->addSql('ALTER TABLE hhonens ADD CONSTRAINT FK_7D675F03E455FCC0 FOREIGN KEY (enseignant_id) REFERENCES penseignant (id)');
        $this->addSql('ALTER TABLE ins_sanctionner ADD CONSTRAINT FK_6DA75BF9DCBA8A24 FOREIGN KEY (agression_id) REFERENCES sous_agression (id)');
        $this->addSql('ALTER TABLE ins_sanctionner ADD CONSTRAINT FK_6DA75BF9316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ins_sanctionner ADD CONSTRAINT FK_6DA75BF9F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ins_sanctionner ADD CONSTRAINT FK_6DA75BF95DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE ins_sanctionner_sanction ADD CONSTRAINT FK_47DBBFFACDA93FD6 FOREIGN KEY (ins_sanctionner_id) REFERENCES ins_sanctionner (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ins_sanctionner_sanction ADD CONSTRAINT FK_47DBBFFA96E0C11A FOREIGN KEY (sanction_id) REFERENCES sanction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE iseance ADD CONSTRAINT FK_EDFD8AE5E3797A94 FOREIGN KEY (seance_id) REFERENCES pl_emptime (id)');
        $this->addSql('ALTER TABLE iseance ADD CONSTRAINT FK_EDFD8AE5E455FCC0 FOREIGN KEY (enseignant_id) REFERENCES penseignant (id)');
        $this->addSql('ALTER TABLE panonymat_actuel ADD CONSTRAINT FK_87848275F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pdiplomes ADD CONSTRAINT FK_F909E7C3F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pdiplomes ADD CONSTRAINT FK_F909E7C35200282E FOREIGN KEY (formation_id) REFERENCES ac_formation (id)');
        $this->addSql('ALTER TABLE pdocument ADD CONSTRAINT FK_ABE182646C97ED8F FOREIGN KEY (nature_demande_id) REFERENCES nature_demande (id)');
        $this->addSql('ALTER TABLE pdocument ADD CONSTRAINT FK_ABE18264FF631228 FOREIGN KEY (etablissement_id) REFERENCES ac_etablissement (id)');
        $this->addSql('ALTER TABLE penseignant ADD CONSTRAINT FK_F788A4C8FE19A1A8 FOREIGN KEY (grade_id) REFERENCES pgrade (id)');
        $this->addSql('ALTER TABLE penseignant_except ADD CONSTRAINT FK_21EAB96BE455FCC0 FOREIGN KEY (enseignant_id) REFERENCES penseignant (id)');
        $this->addSql('ALTER TABLE penseignant_except ADD CONSTRAINT FK_21EAB96B139C32BD FOREIGN KEY (usercreated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE penseignant_except ADD CONSTRAINT FK_21EAB96B5200282E FOREIGN KEY (formation_id) REFERENCES ac_formation (id)');
        $this->addSql('ALTER TABLE penseignant_pr_programmation ADD CONSTRAINT FK_744AE189882AE92 FOREIGN KEY (pr_programmation_id) REFERENCES pr_programmation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE penseignant_pr_programmation ADD CONSTRAINT FK_744AE18D0F570C0 FOREIGN KEY (penseignant_id) REFERENCES penseignant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pensgrille ADD CONSTRAINT FK_7E46E6C6B69AD513 FOREIGN KEY (type_epreuve_id) REFERENCES pnature_epreuve (id)');
        $this->addSql('ALTER TABLE pensgrille ADD CONSTRAINT FK_7E46E6C6139C32BD FOREIGN KEY (usercreated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pensgrille ADD CONSTRAINT FK_7E46E6C6FE19A1A8 FOREIGN KEY (grade_id) REFERENCES pgrade (id)');
        $this->addSql('ALTER TABLE pensgrille ADD CONSTRAINT FK_7E46E6C65200282E FOREIGN KEY (formation_id) REFERENCES ac_formation (id)');
        $this->addSql('ALTER TABLE pgroupe ADD CONSTRAINT FK_C47F22D77A45358C FOREIGN KEY (groupe_id) REFERENCES pgroupe (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A664316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A6647A45358C FOREIGN KEY (groupe_id) REFERENCES pgroupe (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A664DC304035 FOREIGN KEY (salle_id) REFERENCES psalles (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A664122EEC90 FOREIGN KEY (semaine_id) REFERENCES semaine (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A66438FAD351 FOREIGN KEY (user_deleted_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A66496D6BD09 FOREIGN KEY (programmation_id) REFERENCES pr_programmation (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A664F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A6641460EA3F FOREIGN KEY (xsalle_id) REFERENCES psalles (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A664493FDC38 FOREIGN KEY (user_verified_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pl_emptime ADD CONSTRAINT FK_F974A6649CE097A8 FOREIGN KEY (assure_par_id) REFERENCES penseignant (id)');
        $this->addSql('ALTER TABLE pl_emptimens ADD CONSTRAINT FK_4D8F255AE455FCC0 FOREIGN KEY (enseignant_id) REFERENCES penseignant (id)');
        $this->addSql('ALTER TABLE pl_emptimens ADD CONSTRAINT FK_4D8F255AE3797A94 FOREIGN KEY (seance_id) REFERENCES pl_emptime (id)');
        $this->addSql('ALTER TABLE pr_programmation ADD CONSTRAINT FK_BD732A7B543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE pr_programmation ADD CONSTRAINT FK_BD732A7B1F1F2A24 FOREIGN KEY (element_id) REFERENCES ac_element (id)');
        $this->addSql('ALTER TABLE pr_programmation ADD CONSTRAINT FK_BD732A7BF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pr_programmation ADD CONSTRAINT FK_BD732A7B47E7B0A1 FOREIGN KEY (nature_epreuve_id) REFERENCES pnature_epreuve (id)');
        $this->addSql('ALTER TABLE psalles ADD CONSTRAINT FK_B95BEB5C984CE93F FOREIGN KEY (etage_id) REFERENCES petages (id)');
        $this->addSql('ALTER TABLE pv ADD CONSTRAINT FK_D780BF00316B011F FOREIGN KEY (user_updated_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pv ADD CONSTRAINT FK_D780BF00F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pv ADD CONSTRAINT FK_D780BF00543EC5F0 FOREIGN KEY (annee_id) REFERENCES ac_annee (id)');
        $this->addSql('ALTER TABLE pv ADD CONSTRAINT FK_D780BF005577AFDB FOREIGN KEY (semestre_id) REFERENCES ac_semestre (id)');
        $this->addSql('ALTER TABLE sanction ADD CONSTRAINT FK_6D6491AFDCBA8A24 FOREIGN KEY (agression_id) REFERENCES agression (id)');
        $this->addSql('ALTER TABLE sous_agression ADD CONSTRAINT FK_8769C2BADCBA8A24 FOREIGN KEY (agression_id) REFERENCES agression (id)');
        $this->addSql('ALTER TABLE tadmission_document ADD CONSTRAINT FK_7FF4AB51C33F7837 FOREIGN KEY (document_id) REFERENCES pdocument (id)');
        $this->addSql('ALTER TABLE tadmission_document ADD CONSTRAINT FK_7FF4AB518337288 FOREIGN KEY (preinscription_id) REFERENCES tpreinscription (id)');
        $this->addSql('ALTER TABLE tinscription_imp_controle ADD CONSTRAINT FK_15479A7F987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE tinscription_imp_controle ADD CONSTRAINT FK_15479A75DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE tinscription_imp_log ADD CONSTRAINT FK_50C9904FF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE tinscription_imp_log ADD CONSTRAINT FK_50C9904F5DAC5993 FOREIGN KEY (inscription_id) REFERENCES tinscription (id)');
        $this->addSql('ALTER TABLE tpreinscription_pdocument ADD CONSTRAINT FK_48644EF364070F36 FOREIGN KEY (tpreinscription_id) REFERENCES tpreinscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tpreinscription_pdocument ADD CONSTRAINT FK_48644EF3F7278E40 FOREIGN KEY (pdocument_id) REFERENCES pdocument (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tpreinscription_releve_note ADD CONSTRAINT FK_F7B23EACF987D8A8 FOREIGN KEY (user_created_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE tpreinscription_releve_note ADD CONSTRAINT FK_F7B23EACDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES tetudiant (id)');
        $this->addSql('ALTER TABLE tpreinscription_releve_note ADD CONSTRAINT FK_F7B23EACF46CD258 FOREIGN KEY (matiere_id) REFERENCES pmatiere (id)');
        $this->addSql('ALTER TABLE tetudiant ADD type_bac_id INT DEFAULT NULL, ADD academie_id INT DEFAULT NULL, ADD langue_concours_id INT DEFAULT NULL, ADD filiere_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tetudiant ADD CONSTRAINT FK_5F1A7BFDB38A0D28 FOREIGN KEY (academie_id) REFERENCES xacademie (id)');
        $this->addSql('ALTER TABLE tetudiant ADD CONSTRAINT FK_5F1A7BFD180AA129 FOREIGN KEY (filiere_id) REFERENCES xfiliere (id)');
        $this->addSql('ALTER TABLE tetudiant ADD CONSTRAINT FK_5F1A7BFDC3E87EF8 FOREIGN KEY (type_bac_id) REFERENCES xtype_bac (id)');
        $this->addSql('ALTER TABLE tetudiant ADD CONSTRAINT FK_5F1A7BFDFDFFF0BC FOREIGN KEY (langue_concours_id) REFERENCES xlangue (id)');
        $this->addSql('CREATE INDEX IDX_5F1A7BFD180AA129 ON tetudiant (filiere_id)');
        $this->addSql('CREATE INDEX IDX_5F1A7BFDC3E87EF8 ON tetudiant (type_bac_id)');
        $this->addSql('CREATE INDEX IDX_5F1A7BFDB38A0D28 ON tetudiant (academie_id)');
        $this->addSql('CREATE INDEX IDX_5F1A7BFDFDFFF0BC ON tetudiant (langue_concours_id)');
        $this->addSql('ALTER TABLE tinscription ADD groupe_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tinscription ADD CONSTRAINT FK_698E3BDE7A45358C FOREIGN KEY (groupe_id) REFERENCES pgroupe (id)');
        $this->addSql('CREATE INDEX IDX_698E3BDE7A45358C ON tinscription (groupe_id)');
    }
}
