<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_8v6TEwyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.8v6TEwy' shared service.
     *
     * @return \App\Entity\XSerieBac
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\SerieBacController::details()": the $seriebac argument is type-hinted with the non-existent class or interface: "App\\Entity\\XSerieBac".');
    }
}
