<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QNiIFJBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qNiIFJB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qNiIFJB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'operationdet' => ['privates', '.errored..service_locator.qNiIFJB.App\\Entity\\TOperationdet', NULL, 'Cannot autowire service ".service_locator.qNiIFJB": it references class "App\\Entity\\TOperationdet" but no such service exists.'],
        ], [
            'operationdet' => 'App\\Entity\\TOperationdet',
        ]);
    }
}
