<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ngei3M_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ngei3M.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ngei3M.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'salle' => ['privates', '.errored.bun5A5F', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\SallesController::delete()": the $salle argument is type-hinted with the non-existent class or interface: "App\\Entity\\PSalles".'],
        ], [
            'salle' => '?',
        ]);
    }
}
