<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UF9RQtkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.UF9RQtk' shared service.
     *
     * @return \App\Entity\PSalles
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\SallesController::update()": the $salle argument is type-hinted with the non-existent class or interface: "App\\Entity\\PSalles".');
    }
}
