<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZEb2z62Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZEb2z62' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZEb2z62'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'element' => ['privates', '.errored.xNM4IQH', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\ElementController::delete()": the $element argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcElement".'],
        ], [
            'element' => '?',
        ]);
    }
}
