<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LesPpO5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LesPpO5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LesPpO5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chambre' => ['privates', '.errored..service_locator.LesPpO5.App\\Entity\\TChambre', NULL, 'Cannot autowire service ".service_locator.LesPpO5": it references class "App\\Entity\\TChambre" but no such service exists.'],
        ], [
            'chambre' => 'App\\Entity\\TChambre',
        ]);
    }
}
