<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IuXiVUUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IuXiVUU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IuXiVUU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typebac' => ['privates', '.errored.a0CeLJw', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\TypeBacController::delete()": the $typebac argument is type-hinted with the non-existent class or interface: "App\\Entity\\XTypeBac".'],
        ], [
            'typebac' => '?',
        ]);
    }
}
