<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BZPSQ22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bZPSQ22' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bZPSQ22'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'langue' => ['privates', '.errored.Y0EHtQ1', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\LanguesController::details()": the $langue argument is type-hinted with the non-existent class or interface: "App\\Entity\\XLangue".'],
        ], [
            'langue' => '?',
        ]);
    }
}
