<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cKgdrPx.App\Entity\Lit' shared service.
     *
     * @return \App\Entity\Lit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cKgdrPx": it references class "App\\Entity\\Lit" but no such service exists.');
    }
}
