<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTInscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KdQC4yG.App\Entity\TInscription' shared service.
     *
     * @return \App\Entity\TInscription
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KdQC4yG": it references class "App\\Entity\\TInscription" but no such service exists.');
    }
}
