<?php

namespace ContainerK5mLabM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getXBanqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fA3xnus.App\Entity\XBanque' shared service.
     *
     * @return \App\Entity\XBanque
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fA3xnus": it references class "App\\Entity\\XBanque" but no such service exists.');
    }
}
