<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TAdmission extends \App\Entity\TAdmission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'preinscription', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'userUpdated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'fermer', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'inscriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'preinscription', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'userUpdated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'fermer', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TAdmission' . "\0" . 'inscriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TAdmission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?\App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?\App\Entity\PStatut $statut): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreinscription(): ?\App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreinscription', []);

        return parent::getPreinscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreinscription(?\App\Entity\TPreinscription $preinscription): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreinscription', [$preinscription]);

        return parent::setPreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\user $userCreated): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdated', []);

        return parent::getUserUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdated(?\App\Entity\user $userUpdated): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdated', [$userUpdated]);

        return parent::setUserUpdated($userUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getFermer(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFermer', []);

        return parent::getFermer();
    }

    /**
     * {@inheritDoc}
     */
    public function setFermer(?int $fermer): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFermer', [$fermer]);

        return parent::setFermer($fermer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptions', []);

        return parent::getInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\App\Entity\TInscription $inscription): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscription]);

        return parent::addInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\App\Entity\TInscription $inscription): \App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscription]);

        return parent::removeInscription($inscription);
    }

}
