<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PStatut extends \App\Entity\PStatut implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'table0', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'phase0', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'visibleAdmission', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'next', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'active', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'anuller', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'etudiants', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'preinscriptions', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'admissions', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'inscriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'table0', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'phase0', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'visibleAdmission', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'next', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'active', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'anuller', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'etudiants', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'preinscriptions', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'admissions', '' . "\0" . 'App\\Entity\\PStatut' . "\0" . 'inscriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PStatut $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(?string $designation): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation', []);

        return parent::getAbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation(?string $abreviation): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation', [$abreviation]);

        return parent::setAbreviation($abreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTable0(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTable0', []);

        return parent::getTable0();
    }

    /**
     * {@inheritDoc}
     */
    public function setTable0(?string $table0): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTable0', [$table0]);

        return parent::setTable0($table0);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhase0(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhase0', []);

        return parent::getPhase0();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhase0(?string $phase0): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhase0', [$phase0]);

        return parent::setPhase0($phase0);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible(?int $visible): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibleAdmission(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibleAdmission', []);

        return parent::getVisibleAdmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibleAdmission(?int $visibleAdmission): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibleAdmission', [$visibleAdmission]);

        return parent::setVisibleAdmission($visibleAdmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getNext(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNext', []);

        return parent::getNext();
    }

    /**
     * {@inheritDoc}
     */
    public function setNext(?string $next): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNext', [$next]);

        return parent::setNext($next);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnuller(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnuller', []);

        return parent::getAnuller();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnuller(?int $anuller): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnuller', [$anuller]);

        return parent::setAnuller($anuller);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiants(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiants', []);

        return parent::getEtudiants();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtudiant(\App\Entity\TEtudiant $etudiant): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtudiant', [$etudiant]);

        return parent::addEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtudiant(\App\Entity\TEtudiant $etudiant): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtudiant', [$etudiant]);

        return parent::removeEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreinscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreinscriptions', []);

        return parent::getPreinscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreinscription', [$preinscription]);

        return parent::addPreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreinscription', [$preinscription]);

        return parent::removePreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmissions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmissions', []);

        return parent::getAdmissions();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdmission(\App\Entity\TAdmission $admission): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdmission', [$admission]);

        return parent::addAdmission($admission);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdmission(\App\Entity\TAdmission $admission): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdmission', [$admission]);

        return parent::removeAdmission($admission);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptions', []);

        return parent::getInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\App\Entity\TInscription $inscription): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscription]);

        return parent::addInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\App\Entity\TInscription $inscription): \App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscription]);

        return parent::removeInscription($inscription);
    }

}
