<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TInscription extends \App\Entity\TInscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'admission', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'codeAnonymat', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'codeAnonymatRat', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'reserve', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'motif', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'emplacement', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'typeCand', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'salle', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'statutUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userStatutUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'groupe', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'litInscriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'admission', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'promotion', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'codeAnonymat', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'codeAnonymatRat', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'reserve', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'motif', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'emplacement', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'typeCand', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'salle', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'statutUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'userStatutUpdated', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'groupe', '' . "\0" . 'App\\Entity\\TInscription' . "\0" . 'litInscriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TInscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?\App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?\App\Entity\PStatut $statut): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmission(): ?\App\Entity\TAdmission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmission', []);

        return parent::getAdmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmission(?\App\Entity\TAdmission $admission): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmission', [$admission]);

        return parent::setAdmission($admission);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?\App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(?\App\Entity\AcAnnee $annee): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotion(): ?\App\Entity\AcPromotion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotion', []);

        return parent::getPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotion(?\App\Entity\AcPromotion $promotion): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotion', [$promotion]);

        return parent::setPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\user $userCreated): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdated', []);

        return parent::getUserUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdated(?\App\Entity\user $userUpdated): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdated', [$userUpdated]);

        return parent::setUserUpdated($userUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAnonymat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAnonymat', []);

        return parent::getCodeAnonymat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAnonymat(?string $codeAnonymat): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAnonymat', [$codeAnonymat]);

        return parent::setCodeAnonymat($codeAnonymat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAnonymatRat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAnonymatRat', []);

        return parent::getCodeAnonymatRat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAnonymatRat(?string $codeAnonymatRat): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAnonymatRat', [$codeAnonymatRat]);

        return parent::setCodeAnonymatRat($codeAnonymatRat);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserve(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserve', []);

        return parent::getReserve();
    }

    /**
     * {@inheritDoc}
     */
    public function setReserve(?int $reserve): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReserve', [$reserve]);

        return parent::setReserve($reserve);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotif', []);

        return parent::getMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotif(?string $motif): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotif', [$motif]);

        return parent::setMotif($motif);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmplacement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmplacement', []);

        return parent::getEmplacement();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmplacement(int $emplacement): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmplacement', [$emplacement]);

        return parent::setEmplacement($emplacement);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeCand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeCand', []);

        return parent::getTypeCand();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeCand(?string $typeCand): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeCand', [$typeCand]);

        return parent::setTypeCand($typeCand);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalle', []);

        return parent::getSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalle(?string $salle): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalle', [$salle]);

        return parent::setSalle($salle);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserStatutUpdated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserStatutUpdated', []);

        return parent::getUserStatutUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserStatutUpdated(?\App\Entity\user $userStatutUpdated): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserStatutUpdated', [$userStatutUpdated]);

        return parent::setUserStatutUpdated($userStatutUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutUpdated', []);

        return parent::getStatutUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutUpdated(?\DateTimeInterface $statutUpdated): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutUpdated', [$statutUpdated]);

        return parent::setStatutUpdated($statutUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupe(): ?\App\Entity\PGroupe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupe', []);

        return parent::getGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupe(?\App\Entity\PGroupe $groupe): \App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupe', [$groupe]);

        return parent::setGroupe($groupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getLitInscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLitInscriptions', []);

        return parent::getLitInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addLitInscription(\App\Entity\LitInscription $litInscription): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLitInscription', [$litInscription]);

        return parent::addLitInscription($litInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLitInscription(\App\Entity\LitInscription $litInscription): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLitInscription', [$litInscription]);

        return parent::removeLitInscription($litInscription);
    }

}
