<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcFormation extends \App\Entity\AcFormation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'user_created', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'user_updated', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'etablissement', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'code', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'nbr_annee', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'active', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'created', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'acPromotions', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'acAnnees', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'frais', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'tEtudiants', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'assiduite', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'Doyen', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'EtabSec'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'user_created', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'user_updated', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'etablissement', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'code', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'nbr_annee', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'active', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'created', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'acPromotions', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'acAnnees', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'frais', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'tEtudiants', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'assiduite', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'Doyen', '' . "\0" . 'App\\Entity\\AcFormation' . "\0" . 'EtabSec'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AcFormation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\User $user_created): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$user_created]);

        return parent::setUserCreated($user_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdated', []);

        return parent::getUserUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdated(?\App\Entity\User $user_updated): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdated', [$user_updated]);

        return parent::setUserUpdated($user_updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissement(): ?\App\Entity\AcEtablissement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissement', []);

        return parent::getEtablissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtablissement(?\App\Entity\AcEtablissement $etablissement): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtablissement', [$etablissement]);

        return parent::setEtablissement($etablissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(?string $designation): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation', []);

        return parent::getAbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation(?string $abreviation): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation', [$abreviation]);

        return parent::setAbreviation($abreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrAnnee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrAnnee', []);

        return parent::getNbrAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrAnnee(?int $nbr_annee): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrAnnee', [$nbr_annee]);

        return parent::setNbrAnnee($nbr_annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcPromotions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcPromotions', []);

        return parent::getAcPromotions();
    }

    /**
     * {@inheritDoc}
     */
    public function addAcPromotion(\App\Entity\AcPromotion $acPromotion): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcPromotion', [$acPromotion]);

        return parent::addAcPromotion($acPromotion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAcPromotion(\App\Entity\AcPromotion $acPromotion): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAcPromotion', [$acPromotion]);

        return parent::removeAcPromotion($acPromotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcAnnees(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcAnnees', []);

        return parent::getAcAnnees();
    }

    /**
     * {@inheritDoc}
     */
    public function addAcAnnee(\App\Entity\AcAnnee $acAnnee): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAcAnnee', [$acAnnee]);

        return parent::addAcAnnee($acAnnee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAcAnnee(\App\Entity\AcAnnee $acAnnee): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAcAnnee', [$acAnnee]);

        return parent::removeAcAnnee($acAnnee);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrais(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrais', []);

        return parent::getFrais();
    }

    /**
     * {@inheritDoc}
     */
    public function addFrai(\App\Entity\PFrais $frai): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFrai', [$frai]);

        return parent::addFrai($frai);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFrai(\App\Entity\PFrais $frai): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFrai', [$frai]);

        return parent::removeFrai($frai);
    }

    /**
     * {@inheritDoc}
     */
    public function getTEtudiants(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTEtudiants', []);

        return parent::getTEtudiants();
    }

    /**
     * {@inheritDoc}
     */
    public function addTEtudiant(\App\Entity\TEtudiant $tEtudiant): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTEtudiant', [$tEtudiant]);

        return parent::addTEtudiant($tEtudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTEtudiant(\App\Entity\TEtudiant $tEtudiant): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTEtudiant', [$tEtudiant]);

        return parent::removeTEtudiant($tEtudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssiduite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssiduite', []);

        return parent::getAssiduite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssiduite(?int $assiduite): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssiduite', [$assiduite]);

        return parent::setAssiduite($assiduite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoyen(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoyen', []);

        return parent::getDoyen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoyen(?string $Doyen): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoyen', [$Doyen]);

        return parent::setDoyen($Doyen);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtabSec(): ?\App\Entity\AcEtablissement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtabSec', []);

        return parent::getEtabSec();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtabSec(?\App\Entity\AcEtablissement $EtabSec): \App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtabSec', [$EtabSec]);

        return parent::setEtabSec($EtabSec);
    }

}
