<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcAnnee extends \App\Entity\AcAnnee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'user_created', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'user_updated', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'formation', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'code', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'active', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'annee_active_ues', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'validation_academique', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'cloture_academique', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'created', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'preinscriptions', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'inscriptions', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'operationcabs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'user_created', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'user_updated', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'formation', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'code', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'active', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'annee_active_ues', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'validation_academique', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'cloture_academique', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'created', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'preinscriptions', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'inscriptions', '' . "\0" . 'App\\Entity\\AcAnnee' . "\0" . 'operationcabs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AcAnnee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\User $user_created): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$user_created]);

        return parent::setUserCreated($user_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdated', []);

        return parent::getUserUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdated(?\App\Entity\User $user_updated): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdated', [$user_updated]);

        return parent::setUserUpdated($user_updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormation(): ?\App\Entity\AcFormation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormation', []);

        return parent::getFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormation(?\App\Entity\AcFormation $formation): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormation', [$formation]);

        return parent::setFormation($formation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(?string $designation): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeActiveUes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeActiveUes', []);

        return parent::getAnneeActiveUes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeActiveUes(?int $annee_active_ues): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeActiveUes', [$annee_active_ues]);

        return parent::setAnneeActiveUes($annee_active_ues);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationAcademique(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationAcademique', []);

        return parent::getValidationAcademique();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationAcademique(?string $validation_academique): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationAcademique', [$validation_academique]);

        return parent::setValidationAcademique($validation_academique);
    }

    /**
     * {@inheritDoc}
     */
    public function getClotureAcademique(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClotureAcademique', []);

        return parent::getClotureAcademique();
    }

    /**
     * {@inheritDoc}
     */
    public function setClotureAcademique(?string $cloture_academique): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClotureAcademique', [$cloture_academique]);

        return parent::setClotureAcademique($cloture_academique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreinscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreinscriptions', []);

        return parent::getPreinscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreinscription', [$preinscription]);

        return parent::addPreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreinscription', [$preinscription]);

        return parent::removePreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptions', []);

        return parent::getInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\App\Entity\TInscription $inscription): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscription]);

        return parent::addInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\App\Entity\TInscription $inscription): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscription]);

        return parent::removeInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperationcabs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperationcabs', []);

        return parent::getOperationcabs();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperationcab(\App\Entity\TOperationcab $operationcab): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperationcab', [$operationcab]);

        return parent::addOperationcab($operationcab);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperationcab(\App\Entity\TOperationcab $operationcab): \App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperationcab', [$operationcab]);

        return parent::removeOperationcab($operationcab);
    }

}
