<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LitInscription extends \App\Entity\LitInscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'inscription', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'lit', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'start', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'end', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'active', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'UserUpdated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'tOperationcabs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'inscription', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'lit', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'start', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'end', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'active', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'UserUpdated', '' . "\0" . 'App\\Entity\\LitInscription' . "\0" . 'tOperationcabs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LitInscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getInscription(): ?\App\Entity\TInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscription', []);

        return parent::getInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscription(?\App\Entity\TInscription $inscription): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscription', [$inscription]);

        return parent::setInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getLit(): ?\App\Entity\Lit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLit', []);

        return parent::getLit();
    }

    /**
     * {@inheritDoc}
     */
    public function setLit(?\App\Entity\Lit $lit): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLit', [$lit]);

        return parent::setLit($lit);
    }

    /**
     * {@inheritDoc}
     */
    public function getStart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStart', []);

        return parent::getStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setStart(?\DateTimeInterface $start): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStart', [$start]);

        return parent::setStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnd(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnd', []);

        return parent::getEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnd(?\DateTimeInterface $end): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnd', [$end]);

        return parent::setEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?float $active): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\User $userCreated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdated', []);

        return parent::getUserUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdated(?\App\Entity\User $UserUpdated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdated', [$UserUpdated]);

        return parent::setUserUpdated($UserUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getTOperationcabs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTOperationcabs', []);

        return parent::getTOperationcabs();
    }

    /**
     * {@inheritDoc}
     */
    public function addTOperationcab(\App\Entity\TOperationcab $tOperationcab): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTOperationcab', [$tOperationcab]);

        return parent::addTOperationcab($tOperationcab);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTOperationcab(\App\Entity\TOperationcab $tOperationcab): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTOperationcab', [$tOperationcab]);

        return parent::removeTOperationcab($tOperationcab);
    }

}
