<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NatureDemande extends \App\Entity\NatureDemande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'code', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'concours', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'rapport', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'rapport_ordre', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'active', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'etudiants', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'preinscriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'code', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'concours', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'rapport', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'rapport_ordre', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'active', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'etudiants', '' . "\0" . 'App\\Entity\\NatureDemande' . "\0" . 'preinscriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NatureDemande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(?string $designation): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation', []);

        return parent::getAbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation(?string $abreviation): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation', [$abreviation]);

        return parent::setAbreviation($abreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcours(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcours', []);

        return parent::getConcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setConcours(?int $concours): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConcours', [$concours]);

        return parent::setConcours($concours);
    }

    /**
     * {@inheritDoc}
     */
    public function getRapport(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRapport', []);

        return parent::getRapport();
    }

    /**
     * {@inheritDoc}
     */
    public function setRapport(?int $rapport): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRapport', [$rapport]);

        return parent::setRapport($rapport);
    }

    /**
     * {@inheritDoc}
     */
    public function getRapportOrdre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRapportOrdre', []);

        return parent::getRapportOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setRapportOrdre(?int $rapport_ordre): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRapportOrdre', [$rapport_ordre]);

        return parent::setRapportOrdre($rapport_ordre);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiants(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiants', []);

        return parent::getEtudiants();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtudiant(\App\Entity\TEtudiant $etudiant): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtudiant', [$etudiant]);

        return parent::addEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtudiant(\App\Entity\TEtudiant $etudiant): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtudiant', [$etudiant]);

        return parent::removeEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreinscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreinscriptions', []);

        return parent::getPreinscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreinscription', [$preinscription]);

        return parent::addPreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreinscription(\App\Entity\TPreinscription $preinscription): \App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreinscription', [$preinscription]);

        return parent::removePreinscription($preinscription);
    }

}
