<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TOperationcab extends \App\Entity\TOperationcab implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'preinscription', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'reglements', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'operationdets', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'active', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'synFlag', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'dateContable', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'organisme', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'annuler', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'facAnnuler', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'pec', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'npec', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'litInscription'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'preinscription', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'reglements', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'operationdets', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'active', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'synFlag', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'dateContable', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'organisme', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'annuler', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'facAnnuler', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'pec', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'npec', '' . "\0" . 'App\\Entity\\TOperationcab' . "\0" . 'litInscription'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TOperationcab $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreinscription(): ?\App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreinscription', []);

        return parent::getPreinscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreinscription(?\App\Entity\TPreinscription $preinscription): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreinscription', [$preinscription]);

        return parent::setPreinscription($preinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?string $categorie): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?\App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(?\App\Entity\AcAnnee $annee): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation(?string $observation): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$observation]);

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getReglements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReglements', []);

        return parent::getReglements();
    }

    /**
     * {@inheritDoc}
     */
    public function addReglement(\App\Entity\TReglement $reglement): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReglement', [$reglement]);

        return parent::addReglement($reglement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReglement(\App\Entity\TReglement $reglement): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReglement', [$reglement]);

        return parent::removeReglement($reglement);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperationdets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperationdets', []);

        return parent::getOperationdets();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperationdet(\App\Entity\TOperationdet $operationdet): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperationdet', [$operationdet]);

        return parent::addOperationdet($operationdet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperationdet(\App\Entity\TOperationdet $operationdet): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperationdet', [$operationdet]);

        return parent::removeOperationdet($operationdet);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\User $userCreated): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?float $active): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getSynFlag(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSynFlag', []);

        return parent::getSynFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setSynFlag(?float $synFlag): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSynFlag', [$synFlag]);

        return parent::setSynFlag($synFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateContable(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateContable', []);

        return parent::getDateContable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateContable(?int $dateContable): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateContable', [$dateContable]);

        return parent::setDateContable($dateContable);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisme(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisme', []);

        return parent::getOrganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisme(?string $organisme): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisme', [$organisme]);

        return parent::setOrganisme($organisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnuler(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnuler', []);

        return parent::getAnnuler();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnuler(?float $annuler): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnuler', [$annuler]);

        return parent::setAnnuler($annuler);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacAnnuler(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacAnnuler', []);

        return parent::getFacAnnuler();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacAnnuler(?int $facAnnuler): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacAnnuler', [$facAnnuler]);

        return parent::setFacAnnuler($facAnnuler);
    }

    /**
     * {@inheritDoc}
     */
    public function getPec(): ?\App\Entity\Pec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPec', []);

        return parent::getPec();
    }

    /**
     * {@inheritDoc}
     */
    public function setPec(?\App\Entity\Pec $pec): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPec', [$pec]);

        return parent::setPec($pec);
    }

    /**
     * {@inheritDoc}
     */
    public function getNpec(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNpec', []);

        return parent::getNpec();
    }

    /**
     * {@inheritDoc}
     */
    public function setNpec(?string $npec): \App\Entity\TOperationcab
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNpec', [$npec]);

        return parent::setNpec($npec);
    }

    /**
     * {@inheritDoc}
     */
    public function getLitInscription(): ?\App\Entity\litInscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLitInscription', []);

        return parent::getLitInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLitInscription(?\App\Entity\litInscription $litInscription): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLitInscription', [$litInscription]);

        return parent::setLitInscription($litInscription);
    }

}
