<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TPreinscription extends \App\Entity\TPreinscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'etudiant', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'inscriptionValide', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'rangP', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'rangS', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'active', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'mentionnerAdmissible', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'admissions', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'categorieListe', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'admissionListe', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'operationcabs', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'nature', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'userAnnulated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'annulated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'pec', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'pecNumber'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'etudiant', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'code', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'inscriptionValide', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'rangP', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'rangS', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'active', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'mentionnerAdmissible', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'created', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'admissions', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'categorieListe', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'admissionListe', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'operationcabs', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'nature', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'userAnnulated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'annulated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'pec', '' . "\0" . 'App\\Entity\\TPreinscription' . "\0" . 'pecNumber'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TPreinscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?\App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?\App\Entity\PStatut $statut): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant(): ?\App\Entity\TEtudiant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', []);

        return parent::getEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudiant(?\App\Entity\TEtudiant $etudiant): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudiant', [$etudiant]);

        return parent::setEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptionValide(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptionValide', []);

        return parent::getInscriptionValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscriptionValide(?int $inscriptionValide): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscriptionValide', [$inscriptionValide]);

        return parent::setInscriptionValide($inscriptionValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getRangP(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRangP', []);

        return parent::getRangP();
    }

    /**
     * {@inheritDoc}
     */
    public function setRangP(?int $rangP): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRangP', [$rangP]);

        return parent::setRangP($rangP);
    }

    /**
     * {@inheritDoc}
     */
    public function getRangS(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRangS', []);

        return parent::getRangS();
    }

    /**
     * {@inheritDoc}
     */
    public function setRangS(int $rangS): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRangS', [$rangS]);

        return parent::setRangS($rangS);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getMentionnerAdmissible(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMentionnerAdmissible', []);

        return parent::getMentionnerAdmissible();
    }

    /**
     * {@inheritDoc}
     */
    public function setMentionnerAdmissible(?int $mentionnerAdmissible): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMentionnerAdmissible', [$mentionnerAdmissible]);

        return parent::setMentionnerAdmissible($mentionnerAdmissible);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(?\DateTimeInterface $updated): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?\App\Entity\AcAnnee
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(?\App\Entity\AcAnnee $annee): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieListe(): ?\App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieListe', []);

        return parent::getCategorieListe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieListe(?\App\Entity\PStatut $categorieListe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieListe', [$categorieListe]);

        return parent::setCategorieListe($categorieListe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmissionListe(): ?\App\Entity\PStatut
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmissionListe', []);

        return parent::getAdmissionListe();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmissionListe(?\App\Entity\PStatut $admissionListe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmissionListe', [$admissionListe]);

        return parent::setAdmissionListe($admissionListe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperationcab(\App\Entity\TOperationcab $operationcab): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperationcab', [$operationcab]);

        return parent::removeOperationcab($operationcab);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature(): ?\App\Entity\NatureDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', []);

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature(?\App\Entity\NatureDemande $nature): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', [$nature]);

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAnnulated(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAnnulated', []);

        return parent::getUserAnnulated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAnnulated(?\App\Entity\user $userAnnulated): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAnnulated', [$userAnnulated]);

        return parent::setUserAnnulated($userAnnulated);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnulated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnulated', []);

        return parent::getAnnulated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnulated(?\DateTimeInterface $annulated): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnulated', [$annulated]);

        return parent::setAnnulated($annulated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\User $userCreated): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getPec(): ?\App\Entity\Pec
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPec', []);

        return parent::getPec();
    }

    /**
     * {@inheritDoc}
     */
    public function setPec(?\App\Entity\Pec $pec): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPec', [$pec]);

        return parent::setPec($pec);
    }

    /**
     * {@inheritDoc}
     */
    public function getPecNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPecNumber', []);

        return parent::getPecNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPecNumber(?string $pecNumber): \App\Entity\TPreinscription
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPecNumber', [$pecNumber]);

        return parent::setPecNumber($pecNumber);
    }

}
