<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FA3xnusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fA3xnus' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fA3xnus'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'banque' => ['privates', '.errored..service_locator.fA3xnus.App\\Entity\\XBanque', NULL, 'Cannot autowire service ".service_locator.fA3xnus": it references class "App\\Entity\\XBanque" but no such service exists.'],
        ], [
            'banque' => 'App\\Entity\\XBanque',
        ]);
    }
}
