<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_YtYwk3nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ytYwk3n' shared service.
     *
     * @return \App\Entity\XLangue
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\LanguesController::update()": the $langue argument is type-hinted with the non-existent class or interface: "App\\Entity\\XLangue".');
    }
}
