<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CKgdrPxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cKgdrPx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cKgdrPx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lit' => ['privates', '.errored..service_locator.cKgdrPx.App\\Entity\\Lit', NULL, 'Cannot autowire service ".service_locator.cKgdrPx": it references class "App\\Entity\\Lit" but no such service exists.'],
        ], [
            'lit' => 'App\\Entity\\Lit',
        ]);
    }
}
