<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KUgmJmpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.kUgmJmp' shared service.
     *
     * @return \App\Entity\XAcademie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\AcademieController::update()": the $academie argument is type-hinted with the non-existent class or interface: "App\\Entity\\XAcademie".');
    }
}
