<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LGLKc08Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LGLKc08' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LGLKc08'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departement' => ['privates', '.errored..service_locator.LGLKc08.App\\Entity\\AcDepartement', NULL, 'Cannot autowire service ".service_locator.LGLKc08": it references class "App\\Entity\\AcDepartement" but no such service exists.'],
        ], [
            'departement' => 'App\\Entity\\AcDepartement',
        ]);
    }
}
