<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q3TXFYbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q3TXFYb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q3TXFYb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formation' => ['privates', '.errored..service_locator.Q3TXFYb.App\\Entity\\AcFormation', NULL, 'Cannot autowire service ".service_locator.Q3TXFYb": it references class "App\\Entity\\AcFormation" but no such service exists.'],
        ], [
            'formation' => 'App\\Entity\\AcFormation',
        ]);
    }
}
