<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XJHEfkRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xJHEfkR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xJHEfkR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'operationcab' => ['privates', '.errored..service_locator.xJHEfkR.App\\Entity\\TOperationcab', NULL, 'Cannot autowire service ".service_locator.xJHEfkR": it references class "App\\Entity\\TOperationcab" but no such service exists.'],
            'reglement' => ['privates', '.errored..service_locator.xJHEfkR.App\\Entity\\TReglement', NULL, 'Cannot autowire service ".service_locator.xJHEfkR": it references class "App\\Entity\\TReglement" but no such service exists.'],
        ], [
            'operationcab' => 'App\\Entity\\TOperationcab',
            'reglement' => 'App\\Entity\\TReglement',
        ]);
    }
}
