<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcAnneeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vzD4G7E.App\Entity\AcAnnee' shared service.
     *
     * @return \App\Entity\AcAnnee
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vzD4G7E": it references class "App\\Entity\\AcAnnee" but no such service exists.');
    }
}
