<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTAdmissionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2dGTN8Q.App\Entity\TAdmission' shared service.
     *
     * @return \App\Entity\TAdmission
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2dGTN8Q": it references class "App\\Entity\\TAdmission" but no such service exists.');
    }
}
