<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aHd0olU.App\Entity\UsModule' shared service.
     *
     * @return \App\Entity\UsModule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aHd0olU": it references class "App\\Entity\\UsModule" but no such service exists.');
    }
}
