<?php

namespace ContainerEvlLe2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NxvMxSh.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NxvMxSh": it references class "App\\Entity\\User" but no such service exists.');
    }
}
