<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JKYHEsmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jKYHEsm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jKYHEsm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formation' => ['privates', '.errored..service_locator.jKYHEsm.App\\Entity\\AcFormation', NULL, 'Cannot autowire service ".service_locator.jKYHEsm": it references class "App\\Entity\\AcFormation" but no such service exists.'],
            'paiement' => ['privates', '.errored..service_locator.jKYHEsm.App\\Entity\\XModalites', NULL, 'Cannot autowire service ".service_locator.jKYHEsm": it references class "App\\Entity\\XModalites" but no such service exists.'],
        ], [
            'formation' => 'App\\Entity\\AcFormation',
            'paiement' => 'App\\Entity\\XModalites',
        ]);
    }
}
