<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XsMPLreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XsMPLre' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XsMPLre'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etudiant' => ['privates', '.errored..service_locator.XsMPLre.App\\Entity\\TEtudiant', NULL, 'Cannot autowire service ".service_locator.XsMPLre": it references class "App\\Entity\\TEtudiant" but no such service exists.'],
        ], [
            'etudiant' => 'App\\Entity\\TEtudiant',
        ]);
    }
}
