<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KjKYqyJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KjKYqyJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KjKYqyJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'semestre' => ['privates', '.errored..service_locator.KjKYqyJ.App\\Entity\\AcSemestre', NULL, 'Cannot autowire service ".service_locator.KjKYqyJ": it references class "App\\Entity\\AcSemestre" but no such service exists.'],
        ], [
            'semestre' => 'App\\Entity\\AcSemestre',
        ]);
    }
}
