<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcDepartementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LGLKc08.App\Entity\AcDepartement' shared service.
     *
     * @return \App\Entity\AcDepartement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LGLKc08": it references class "App\\Entity\\AcDepartement" but no such service exists.');
    }
}
