<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPFraisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kbeyOkT.App\Entity\PFrais' shared service.
     *
     * @return \App\Entity\PFrais
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kbeyOkT": it references class "App\\Entity\\PFrais" but no such service exists.');
    }
}
