<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTEtudiantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XsMPLre.App\Entity\TEtudiant' shared service.
     *
     * @return \App\Entity\TEtudiant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XsMPLre": it references class "App\\Entity\\TEtudiant" but no such service exists.');
    }
}
