<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTOperationdetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qNiIFJB.App\Entity\TOperationdet' shared service.
     *
     * @return \App\Entity\TOperationdet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qNiIFJB": it references class "App\\Entity\\TOperationdet" but no such service exists.');
    }
}
