<?php

namespace ContainerRxCszxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTBrdpaiementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eP3ATxI.App\Entity\TBrdpaiement' shared service.
     *
     * @return \App\Entity\TBrdpaiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eP3ATxI": it references class "App\\Entity\\TBrdpaiement" but no such service exists.');
    }
}
