<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_ZY2nkfqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ZY2nkfq' shared service.
     *
     * @return \App\Entity\PEnseignant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\EnseignantController::delete()": the $enseignant argument is type-hinted with the non-existent class or interface: "App\\Entity\\PEnseignant".');
    }
}
