<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pt7SU7EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pt7SU7E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pt7SU7E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'module' => ['privates', '.errored.zmRK0Ri', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\ModuleController::details()": the $module argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcModule".'],
        ], [
            'module' => '?',
        ]);
    }
}
