<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_H3uXOc7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.H3uXOc7' shared service.
     *
     * @return \App\Entity\AcElement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\ElementController::update()": the $element argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcElement".');
    }
}
