<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PzEWOcyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PzEWOcy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PzEWOcy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'salle' => ['privates', '.errored.UF9RQtk', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\SallesController::update()": the $salle argument is type-hinted with the non-existent class or interface: "App\\Entity\\PSalles".'],
        ], [
            'salle' => '?',
        ]);
    }
}
