<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tpx2_FLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tpx2.fL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tpx2.fL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'operationcab' => ['privates', '.errored..service_locator.Tpx2.fL.App\\Entity\\TOperationcab', NULL, 'Cannot autowire service ".service_locator.Tpx2.fL": it references class "App\\Entity\\TOperationcab" but no such service exists.'],
        ], [
            'operationcab' => 'App\\Entity\\TOperationcab',
        ]);
    }
}
