<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcFormation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jKYHEsm.App\Entity\AcFormation' shared service.
     *
     * @return \App\Entity\AcFormation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jKYHEsm": it references class "App\\Entity\\AcFormation" but no such service exists.');
    }
}
