<?php

namespace ContainerTHXOSLY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTChambreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LesPpO5.App\Entity\TChambre' shared service.
     *
     * @return \App\Entity\TChambre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LesPpO5": it references class "App\\Entity\\TChambre" but no such service exists.');
    }
}
