<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EP3ATxIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eP3ATxI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eP3ATxI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'borderaux' => ['privates', '.errored..service_locator.eP3ATxI.App\\Entity\\TBrdpaiement', NULL, 'Cannot autowire service ".service_locator.eP3ATxI": it references class "App\\Entity\\TBrdpaiement" but no such service exists.'],
        ], [
            'borderaux' => 'App\\Entity\\TBrdpaiement',
        ]);
    }
}
