<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5RNJ4dYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5RNJ4dY' shared service.
     *
     * @return \App\Entity\XFiliere
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\FiliereController::details()": the $filiere argument is type-hinted with the non-existent class or interface: "App\\Entity\\XFiliere".');
    }
}
