<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_AB13cxpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.aB13cxp' shared service.
     *
     * @return \App\Entity\AcModule
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Parametre\\ModuleController::update()": the $module argument is type-hinted with the non-existent class or interface: "App\\Entity\\AcModule".');
    }
}
