<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JZQeeEUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JZQeeEU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JZQeeEU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'langue' => ['privates', '.errored.uqkeXsn', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\LanguesController::delete()": the $langue argument is type-hinted with the non-existent class or interface: "App\\Entity\\XLangue".'],
        ], [
            'langue' => '?',
        ]);
    }
}
