<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KcTRyykService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kcTRyyk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kcTRyyk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'preinscriptionnote' => ['privates', '.errored.uPjJulf', NULL, 'Cannot determine controller argument for "App\\Controller\\Etudiant\\EtudiantController::removeMatiere()": the $preinscriptionnote argument is type-hinted with the non-existent class or interface: "App\\Entity\\TPreinscriptionReleveNote".'],
        ], [
            'preinscriptionnote' => '?',
        ]);
    }
}
