<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_462OWMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4_62OWM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4_62OWM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filiere' => ['privates', '.errored.u.Elj23', NULL, 'Cannot determine controller argument for "App\\Controller\\Parametre\\FiliereController::update()": the $filiere argument is type-hinted with the non-existent class or interface: "App\\Entity\\XFiliere".'],
        ], [
            'filiere' => '?',
        ]);
    }
}
