<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RqS8q2tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RqS8q2t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RqS8q2t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modalites' => ['privates', '.errored..service_locator.RqS8q2t.App\\Entity\\XModalites', NULL, 'Cannot autowire service ".service_locator.RqS8q2t": it references class "App\\Entity\\XModalites" but no such service exists.'],
        ], [
            'modalites' => 'App\\Entity\\XModalites',
        ]);
    }
}
