<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcSemestre2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KjKYqyJ.App\Entity\AcSemestre' shared service.
     *
     * @return \App\Entity\AcSemestre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KjKYqyJ": it references class "App\\Entity\\AcSemestre" but no such service exists.');
    }
}
