<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPEtagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EqwgwxF.App\Entity\PEtages' shared service.
     *
     * @return \App\Entity\PEtages
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EqwgwxF": it references class "App\\Entity\\PEtages" but no such service exists.');
    }
}
