<?php

namespace ContainerJ0x3r7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTOperationcab3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xJHEfkR.App\Entity\TOperationcab' shared service.
     *
     * @return \App\Entity\TOperationcab
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xJHEfkR": it references class "App\\Entity\\TOperationcab" but no such service exists.');
    }
}
