<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0x3r7g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0x3r7g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ0x3r7g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ0x3r7g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ0x3r7g\App_KernelDevDebugContainer([
    'container.build_hash' => 'J0x3r7g',
    'container.build_id' => 'c16e45a7',
    'container.build_time' => 1720195634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0x3r7g');
