<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDI9MJNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDI9MJNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDI9MJNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDI9MJNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDI9MJNj\App_KernelDevDebugContainer([
    'container.build_hash' => 'DI9MJNj',
    'container.build_id' => 'a3396381',
    'container.build_time' => 1720628133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDI9MJNj');
