<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHXOSLY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHXOSLY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTHXOSLY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTHXOSLY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTHXOSLY\App_KernelDevDebugContainer([
    'container.build_hash' => 'THXOSLY',
    'container.build_id' => '532bbdb2',
    'container.build_time' => 1721052343,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHXOSLY');
