<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_axios_index_js-node_m-b3a05b.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_axios_index_js-node_m-b3a05b.css',
                '/build/app.css',
            ],
        ],
        'login' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/login.js',
            ],
            'css' => [
                '/build/login.css',
            ],
        ],
        'preinscription' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/preinscription.js',
            ],
        ],
        'gestionPreinscription' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/gestionPreinscription.js',
            ],
        ],
        'admission' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/admission.js',
            ],
        ],
        'gestionadmission' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/gestionadmission.js',
            ],
        ],
        'inscription' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/inscription.js',
            ],
        ],
        'facture' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/facture.js',
            ],
        ],
        'bordereau' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/bordereau.js',
            ],
        ],
        'reglement' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_i-c7a83c.js',
                '/build/reglement.js',
            ],
        ],
        'departement' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/departement.js',
            ],
        ],
        'etage' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/etage.js',
            ],
        ],
        'chambre' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_string_search_js.js',
                '/build/chambre.js',
            ],
        ],
        'synchronisation' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/synchronisation.js',
            ],
        ],
        'user' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2de272.js',
                '/build/vendors-node_modules_core-js_modules_es_array_find_js-node_modules_core-js_modules_es_array_map_js.js',
                '/build/user.js',
            ],
        ],
    ],
],

]];
